// @ts-check
/**
 * Syntax themes: the highlight.js theme collection, converted at build time
 * (scripts/syntax-themes.js) and loaded on demand as constructable stylesheets.
 *
 * Only names present in the generated index are ever turned into URLs.
 *
 * @module core/syntax-themes
 */
import { getConfig } from './config.js';
import { SYNTAX_THEME_INDEX } from './syntax-theme-index.js';

/** Base URL of the theme files, set by the entry point. */
let defaultBaseUrl = '';

/** @type {Map<string, Promise<CSSStyleSheet | null>>} */
const loading = new Map();
/** @type {Map<string, CSSStyleSheet>} */
const loaded = new Map();

/**
 * Sets the default base URL of `syntax-themes/*.css` (called by the entry points).
 *
 * @param {string} url
 */
export function setDefaultSyntaxThemesUrl(url) {
  defaultBaseUrl = url;
}

/**
 * Normalizes and validates a syntax theme name.
 *
 * @param {string | null | undefined} name - e.g. `"github-dark"`, `"base16/dracula"`.
 * @returns {string | null}
 */
export function resolveSyntaxTheme(name) {
  if (typeof name !== 'string') return null;
  const key = name.trim().toLowerCase().replace(/\//g, '-');
  if (!key || key.length > 60) return null;
  return Object.prototype.hasOwnProperty.call(SYNTAX_THEME_INDEX, key) ? key : null;
}

/**
 * Lists the available syntax theme names.
 *
 * @returns {string[]}
 */
export function listSyntaxThemes() {
  return Object.keys(SYNTAX_THEME_INDEX);
}

/**
 * Returns a loaded theme stylesheet, or `undefined` when it is not loaded yet.
 *
 * @param {string} name - Resolved name.
 * @returns {CSSStyleSheet | undefined}
 */
export function loadedSyntaxTheme(name) {
  return loaded.get(name);
}

/**
 * Loads a syntax theme stylesheet once and shares it between all elements.
 *
 * @param {string} name - Resolved name (see {@link resolveSyntaxTheme}).
 * @returns {Promise<CSSStyleSheet | null>}
 */
export function loadSyntaxTheme(name) {
  const existing = loading.get(name);
  if (existing) return existing;
  const promise = fetchTheme(name);
  loading.set(name, promise);
  return promise;
}

/**
 * @param {string} name
 * @returns {Promise<CSSStyleSheet | null>}
 */
async function fetchTheme(name) {
  const base = getConfig().syntaxThemesUrl || defaultBaseUrl;
  if (!base) return null;
  try {
    const url = new URL(
      `${name}.css`,
      new URL(base.endsWith('/') ? base : `${base}/`, document.baseURI),
    );
    if (url.protocol !== 'https:' && url.protocol !== 'http:') return null;
    const response = await fetch(url.href, { credentials: 'same-origin' });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const css = await response.text();
    // Theme files are generated by the build and contain no @import or url(); a
    // constructable stylesheet would refuse @import anyway.
    const sheet = new CSSStyleSheet();
    sheet.replaceSync(css);
    loaded.set(name, sheet);
    return sheet;
  } catch (error) {
    console.warn(`[vitrine] Could not load the "${name}" syntax theme.`, error);
    loading.delete(name);
    return null;
  }
}
