/**
 * Generates THIRD_PARTY_NOTICES.md with the full license text of every third-party
 * component, at the exact installed version. `--check` fails when the file is stale.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { thirdParty } from './third-party.js';

const components = await thirdParty();
const parts = [
  '# Third-party notices',
  '',
  'Vitrine includes the following third-party components. This file is generated by',
  '`scripts/generate-notices.js` from the installed packages; run `npm run notices` after',
  'changing a dependency.',
  '',
  '| Component | Version | License | Used for | Shipped in |',
  '|---|---|---|---|---|',
  ...components.map(
    (c) => `| [${c.name}](${c.url}) | ${c.version} | ${c.license} | ${c.use} | ${c.where} |`,
  ),
  '',
  'DOMPurify’s distribution also contains a small helper from regenerator-runtime',
  '(Copyright (c) 2014-present, Facebook, Inc.; MIT License), credited in the bundle header.',
];
for (const c of components) {
  const text = (await readFile(new URL(`../${c.licenseFile}`, import.meta.url), 'utf8')).trim();
  parts.push(
    '',
    '---',
    '',
    `## ${c.name} ${c.version}`,
    '',
    `License: ${c.license}. Source: ${c.url}`,
    '',
    '```text',
    text,
    '```',
  );
  // Apache-2.0 components ship a NOTICE file that must be reproduced.
  if (c.noticeFile) {
    const notice = (await readFile(new URL(`../${c.noticeFile}`, import.meta.url), 'utf8')).trim();
    parts.push('', 'NOTICE:', '', '```text', notice, '```');
  }
}
const output = `${parts.join('\n')}\n`;
const target = new URL('../THIRD_PARTY_NOTICES.md', import.meta.url);

if (process.argv.includes('--check')) {
  if ((await readFile(target, 'utf8').catch(() => '')) !== output) {
    console.error('THIRD_PARTY_NOTICES.md is out of date. Run `npm run notices`.');
    process.exit(1);
  }
  console.log('THIRD_PARTY_NOTICES.md is up to date.');
} else {
  await writeFile(target, output);
  console.log(`THIRD_PARTY_NOTICES.md: ${components.length} components`);
}
