/**
 * Generates design-tokens.json (W3C Design Tokens format) from the theme and token CSS
 * files, so the website and future tooling share the exact values the components use.
 *
 * `--check` fails when the committed file is out of date (used in CI).
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const themesDir = new URL('src/styles/themes/', root);
const out = new URL('design-tokens.json', root);

/** @param {string} value */
function type(value) {
  if (/^(#|rgb|hsl|oklch|color-mix|transparent)/i.test(value)) return 'color';
  if (/^\d+(\.\d+)?(px|rem|em)$/.test(value)) return 'dimension';
  if (/^\d+ms$/.test(value)) return 'duration';
  if (/^cubic-bezier/.test(value)) return 'cubicBezier';
  if (/^\d+(\.\d+)?$/.test(value)) return 'number';
  if (/px .*rgba?\(|^0 0 0/.test(value)) return 'shadow';
  return 'fontFamily';
}

const tokens = {
  $description: 'Vitrine design tokens. Generated by scripts/generate-tokens.js — do not edit.',
};

// Theme-independent tokens: `--_x: var(--vt-x, default)` in tokens.css.
const base = await readFile(new URL('src/styles/tokens.css', root), 'utf8');
const shared = {};
for (const [, name, value] of base.matchAll(
  /--_[a-z0-9-]+:\s*var\(\s*--vt-([a-z0-9-]+),\s*([^;]+?)\s*\);/gs,
)) {
  const clean = value.replace(/\s+/g, ' ').trim();
  shared[name] = { $type: type(clean), $value: clean };
}
tokens.base = shared;

// Themes.
tokens.themes = {};
for (const file of (await readdir(themesDir)).filter((f) => f.endsWith('.css')).sort()) {
  const css = await readFile(new URL(file, themesDir), 'utf8');
  const name = /\[data-theme='([a-z0-9-]+)'\]/.exec(css)[1];
  const scheme = /color-scheme:\s*(light|dark)/.exec(css)[1];
  const theme = {
    $description: /\/\*\s*(.+?)\s*\*\//.exec(css)?.[1] ?? name,
    'color-scheme': { $value: scheme },
  };
  for (const [, token, value] of css.matchAll(/--vt-([a-z0-9-]+)\s*:\s*([^;]+);/g)) {
    theme[token] = { $type: type(value.trim()), $value: value.trim() };
  }
  tokens.themes[name] = theme;
}

const json = `${JSON.stringify(tokens, null, 2)}\n`;
if (process.argv.includes('--check')) {
  const current = await readFile(out, 'utf8').catch(() => '');
  if (current !== json) {
    console.error('design-tokens.json is out of date. Run `npm run tokens`.');
    process.exit(1);
  }
  console.log('design-tokens.json is up to date.');
} else {
  await writeFile(out, json);
  console.log(
    `design-tokens.json: ${Object.keys(shared).length} base tokens, ${Object.keys(tokens.themes).length} themes`,
  );
}
